# Generated by Django 4.2.6 on 2023-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="имя")),
                ("price", models.IntegerField(verbose_name="цена")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="описание",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="адрес картинки")),
                (
                    "discount",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="скидка",
                    ),
                ),
                (
                    "ozon_id",
                    models.IntegerField(
                        unique=True, verbose_name="id продукта"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ("name", "price"),
            },
        ),
    ]
