# Generated by Django 4.2.6 on 2023-10-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="описание"
            ),
        ),
    ]
